services:
    db:
        image: postgres:14
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        depends_on:
            - db
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    api:
        build: .
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_SERVER=db
            - POSTGRES_PORT=5432
            - REDIS_HOST=redis
        depends_on:
            - db
            - redis

volumes:
    postgres_data:
